name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create-DB
        run: docker-compose up -d
        env:
          DB_USER: ${{ secrets.DBUSER }}
          DB_PASSWORD: ${{ secrets.DBPASSWORD }}
          PG_PORT: ${{ secrets.PGPORT }}

      - name: Stop containers
        if: always()
        run: docker-compose rm -f "docker-compose.yml
