name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "19.x"

      - name: Create-DB
        run: docker-compose up 
        env:
          DB_USER: ${{ secrets.DBUSER }}
          DB_PASSWORD: ${{ secrets.DBPASSWORD }}
          PG_PORT: ${{ secrets.PGPORT }}

      - name: install dependencies
        run: npm install

      - name: execute integration tests
        run: npm run test
        env:
          PORT: ${{ secrets.PORT }}
          DB_HOST: ${{ secrets.DBHOST }}
          DB_PORT: ${{ secrets.DB_PORT}}
          DB_USER: ${{ secrets.DBUSER }}
          DB_PASSWORD: ${{ secrets.DBPASSWORD }}

      - name: Stop containers
        if: always()
        run: docker-compose rm -f "docker-compose.yml